logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
zuul:
  routes:
    ks-supersync-unasapi:
      url: https://unasapi.herokuapp.com/
      serviceId: ks-supersync-unasapi