hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
    ReadTimeout: 10000
zuul:
  ribbon:
    eager-load:
      enabled: true

    